# Generated by Django 5.0.3 on 2024-04-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
