# Generated by Django 5.0.3 on 2024-04-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=64)),
            ],
        ),
    ]
