# Generated by Django 5.0.3 on 2024-04-06 17:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('opened_on', models.DateTimeField()),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('confidential_notes', models.TextField(null=True)),
                ('resolved_on', models.DateTimeField(null=True)),
                ('resolution_notes', models.TextField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('assignment_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.team')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to=settings.AUTH_USER_MODEL)),
                ('configuration_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.configuration_item')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.location')),
                ('priority', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.priority')),
                ('resolved_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resolved_by', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.service')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.state')),
            ],
        ),
    ]
