# Generated by Django 5.0.3 on 2024-04-08 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_item',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
