# Generated by Django 5.0.3 on 2024-04-08 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_configuration_item_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='opened_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
