# Generated by Django 5.0.3 on 2024-04-20 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_model_alter_configuration_item_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='assignment_group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.team'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='caller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='configuration_item',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.configuration_item'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.priority'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.service'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
