# Generated by Django 5.0.3 on 2024-04-20 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_incident_assignment_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='assignment_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.team'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='configuration_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.configuration_item'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.priority'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.service'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.state'),
        ),
    ]
