# Generated by Django 5.0.3 on 2024-05-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='type',
        ),
    ]
