# Generated by Django 5.0.3 on 2024-05-02 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_remove_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
