# Generated by Django 5.0.3 on 2024-05-05 07:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_note_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role', to='tickets.role'),
        ),
    ]
