# Generated by Django 5.0.3 on 2024-05-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_alter_team_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='support_groups',
            field=models.ManyToManyField(to='tickets.team'),
        ),
    ]
